SAMPLES_COLUMN_MAPPING = {
    "Sample.ID": "sample_id",
    "Aluminium": "Al",
    "Aluminum": "Al",
    "Boron": "B",
    "Calcium": "Ca",
    "Chloride": "Cl",
    "Copper": "Cu",
    "Iron": "Fe",
    "Magnesium": "Mg",
    "Manganese": "Mn",
    "Nitrogen": "N",
    "Phosphorus": "P",
    "Phosphorous": "P",
    "Potassium": "K",
    "Sodium": "Na",
    "Sulfur": "S",
    "Zinc": "Zn",
}

ELEMENT_COLUMNS = [
    "Al",
    "B",
    "Ca",
    "Cl",
    "Cu",
    "Fe",
    "Mg",
    "Mn",
    "N",
    "P",
    "K",
    "Na",
    "S",
    "Zn",
]

ELEMENT_UNITS = {
    "Al": "ppm",
    "B": "ppm",
    "Ca": "pct",
    "Cl": "pct",
    "Cu": "ppm",
    "Fe": "ppm",
    "Mg": "pct",
    "Mn": "ppm",
    "N": "pct",
    "P": "pct",
    "K": "pct",
    "Na": "pct",
    "S": "pct",
    "Zn": "ppm",
}

ELEMENT_TYPES = {
    "Ca": "macro",
    "Mg": "macro",
    "N": "macro",
    "P": "macro",
    "K": "macro",
    "S": "macro",
    "Cl": "micro",
    "Na": "micro",
    "Al": "micro",
    "B": "micro",
    "Cu": "micro",
    "Fe": "micro",
    "Mn": "micro",
    "Zn": "micro",
}

ELEMENT_SPEARMAN_CORRELATIONS = {
    ("Ca", "Zn"): -0.553,
    ("B", "Ca"): 0.565,
    ("B", "P"): -0.756,
    ("Ca", "Cu"): -0.519,
    ("Ca", "Mg"): 0.704,
    ("Mg", "K"): -0.825,
    ("Mg", "N"): -0.606,
    ("Ca", "P"): -0.637,
    ("Al", "P"): -0.532,
    ("N", "P"): 0.832,
    ("N", "S"): 0.648,
    ("K", "N"): 0.583,
    ("Fe", "K"): -0.295,
    ("Mn", "P"): -0.315,
    ("K", "Mn"): -0.294,
    ("P", "S"): 0.761,
    ("K", "S"): 0.432,
}

ELEMENT_WEIGHTS = {
    "Al": 1.4,
    "B": 0.8,
    "Ca": 1.4,
    "Cl": 0,
    "Cu": 1.4,
    "Fe": 1.4,
    "Mg": 1.4,
    "Mn": 0.8,
    "N": 0.6,
    "P": 0.6,
    "K": 0.6,
    "Na": 0,
    "S": 1.4,
    "Zn": 1.4
}
