settings:
  log_level: "INFO"
  leaf_samples_folder_path: "data/leaf_samples"
  results_folder_path: "reports/results/pls"

read_data:
  LeafSampleReader:
    read_selected_csvs:
      leaf_states: [fresh]
      seasons: [1,2,3,4]
  DataCleaner:
  # You invoke drop_null_data, impute_data and remove_outliers in read_data stage and/or in TestTrainSplit stage
  # Note that remove_outliers can only be used for training data in TestTrainSplit stage
    drop_null_data:
        row_threshold: 0.5
        target_col_threshold: 0.5
        feature_col_threshold: 0.5
        reset_index: False

TestTrainSplit:
  method: "stratified"
  train:
    DataCleaner:
      impute_data:
        target_method: "knn"
        feature_method: "neighbour_avg"
      remove_outliers:
        method: ~ #use ~ for exluding the method or commenting the entire method
        feature_outlier_threshold: 95
  test:
    DataCleaner:
      impute_data:
        target_method: "knn"
        feature_method: "neighbour_avg"
      
TargetScaler:
  scaling_methods:
    Al: quantile # use ~ for not scaling
    B: quantile
    Ca: quantile
    Cl: quantile
    Cu: quantile
    Fe: quantile
    Mg: quantile
    Mn: quantile
    N: quantile
    P: quantile
    K: quantile
    Na: quantile
    S: quantile
    Zn: quantile

BaselineCorrector:
  method: "als" # use ~ for not correcting the baseline
  mean_based: False
  parameters:
    #poly_order: 2
     lam: 100000
     p: 0.1
     niter: 5
     als_precalculated_folder: "optimised_als_corrected_samples_fresh"

PeakFeatureExtraction:
  min_prominence: 0.01
  show_plot: True
  
DataReducer:
  method: ~ # use ~ for not reducing the data
  parameters:
    reset_index: True # need to keep as True to avoid null errors at the end of the pipeline
    n_components: 20
    # wavelength_bins: 20 # if using binning

RegressionModels:
  model_type: "PLS"
  k_fold: 10
  param_grid:
    n_components: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45]

Evaluate:
  metrics:  [r2, mse, rmse, rrmse, mae, mape, wrmse]
  weights:
    Al: 0.6
    B: 0.8
    Ca: 0.6
    Cl: 0
    Cu: 0.6
    Fe: 0.6
    Mg: 0.6
    Mn: 0.8
    N: 1
    P: 1
    K: 1
    Na: 0
    S: 0.6
    Zn: 0.6